#!/usr/bin/env zsh
# ralph.sh — Deck Phase 2 Harness Core Builder
# Executes tasks from PRD.md one at a time in headless mode.
# Runs sanity checks between phases. Self-heals on build failures (max 3 attempts).
# Commits once per phase. Tracks findings in FINDINGS.md.

set -euo pipefail

# ── Trap Ctrl+C to exit cleanly ──────────────────────────
cleanup() {
  echo ""
  echo -e "\033[0;31m[$(date '+%Y-%m-%d %H:%M:%S')] Ralph interrupted. Exiting.\033[0m"
  kill 0 2>/dev/null
  exit 130
}
trap cleanup SIGINT SIGTERM

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
PRD_FILE="$PROJECT_DIR/PRD.md"
FINDINGS_FILE="$PROJECT_DIR/FINDINGS.md"
LOG_FILE="$PROJECT_DIR/ralph.log"
MAX_FIX_ATTEMPTS=3

# ── Colors ────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# ══════════════════════════════════════════════════════════
#  Task list — format: "task_id|phase|description"
#  Must match PRD.md checkboxes exactly.
# ══════════════════════════════════════════════════════════
TASKS=(
  "1.1|1|Create blueprint domain types"
  "1.2|1|Create blueprint YAML loader"
  "1.3|1|Create shipped default blueprints"
  "1.4|1|Create blueprint registry"
  "2.1|2|Create blueprint execution engine"
  "2.2|2|Create blueprint persistence (DB store)"
  "3.1|3|Create rules domain types"
  "3.2|3|Create rules loader and matcher"
  "4.1|4|Create tool curator types"
  "4.2|4|Create tool curator"
  "5.1|5|Create quality gate types and runner"
  "5.2|5|Create quality gate runner"
  "6.1|6|Wire harness into daemon"
  "6.2|6|Add blueprint API endpoints"
  "6.3|6|Add harness unit tests"
)

# ══════════════════════════════════════════════════════════
#  Phase names (for commit messages and logging)
# ══════════════════════════════════════════════════════════
get_phase_name() {
  case "$1" in
    1) echo "Blueprint Types & Loader" ;;
    2) echo "Blueprint Engine" ;;
    3) echo "Scoped Rules Engine" ;;
    4) echo "Tool Curator" ;;
    5) echo "Quality Gate Runner" ;;
    6) echo "Integration & Wiring" ;;
  esac
}

# ── Helpers ───────────────────────────────────────────────
timestamp() { date "+%Y-%m-%d %H:%M:%S" }

log() {
  echo -e "${CYAN}[$(timestamp)]${NC} $1" | tee -a "$LOG_FILE"
}

log_success() {
  echo -e "${GREEN}[$(timestamp)] ✓${NC} $1" | tee -a "$LOG_FILE"
}

log_error() {
  echo -e "${RED}[$(timestamp)] ✗${NC} $1" | tee -a "$LOG_FILE"
}

log_phase() {
  echo "" | tee -a "$LOG_FILE"
  echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a "$LOG_FILE"
  echo -e "${BOLD}${BLUE}  Phase $1${NC}" | tee -a "$LOG_FILE"
  echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a "$LOG_FILE"
}

# Check if a task is already marked done in PRD.md
is_task_done() {
  local task_id="$1"
  grep -q "\[x\] \*\*${task_id}\*\*" "$PRD_FILE" 2>/dev/null
}

# Mark a task as done in PRD.md ([ ] → [x])
# NOTE: macOS sed syntax. On Linux, change `sed -i ''` to `sed -i`
mark_task_done() {
  local task_id="$1"
  sed -i '' "s/- \[ \] \*\*${task_id}\*\*/- [x] **${task_id}**/" "$PRD_FILE"
}

# ── Init findings file ────────────────────────────────────
init_findings() {
  if [[ ! -f "$FINDINGS_FILE" ]]; then
    cat > "$FINDINGS_FILE" << 'EOF'
# Phase 2: Harness Core — Findings & Decisions Log

Auto-generated by ralph. Each task logs its decisions and findings here.
Phase 1 findings: `docs/phase1/FINDINGS.md`

---

EOF
    log "Created FINDINGS.md"
  fi
}

# ══════════════════════════════════════════════════════════
#  Task execution prompt
# ══════════════════════════════════════════════════════════
run_task() {
  local task_id="$1"
  local description="$2"

  local prompt="You are implementing a Go project called Deck — an agentic workflow orchestrator.

PROJECT DIRECTORY: $PROJECT_DIR

YOUR TASK: Execute task **${task_id}** — \"${description}\"

Read the full task specification from PRD.md (task ${task_id}) and implement it exactly.
Read FINDINGS.md to understand any decisions or context from previous tasks.
Read docs/phase1/FINDINGS.md for context from Phase 1 decisions.

RULES:
- Only do what this specific task requires. Do not touch other tasks.
- After completing the task, append your findings/decisions to FINDINGS.md under a heading '## Task ${task_id}: ${description}'.
  Include: what you did, any decisions you made, any issues encountered, and any notes for future tasks. Keep it concise (3-8 bullet points).
- If you encounter something that should be deferred to a later phase (e.g., a feature that depends on unbuilt infrastructure, a TODO that isn't needed yet), append it to docs/DEFERRED.md under the '## From Phase 2 (Harness Core)' section. Follow the existing format: item name as h3, with original scope, what exists, what's missing, deferred to, and reason.
- Do NOT commit anything to git.
- Do NOT run the dev server or any long-running processes.
- If a task says to install packages, actually run the install command.
- If a task says to create a file, create the file with the full implementation — not stubs or TODOs.
- Make sure all types and imports are correct. Every Go file must compile.
- IMPORTANT: Before using any Go library you're unfamiliar with, use the context7 MCP tools to look up documentation:
  1. First call mcp__plugin_context7_context7__resolve-library-id to find the library ID (e.g., for 'modernc.org/sqlite', 'github.com/spf13/cobra', 'gopkg.in/yaml.v3')
  2. Then call mcp__plugin_context7_context7__query-docs with that ID and a specific query to get usage examples and API details
  This applies to ALL external libraries and any Go stdlib packages you're not certain about.
- Use modernc.org/sqlite (pure Go driver, no CGo). The driver name is \"sqlite\". Do NOT use mattn/go-sqlite3.
- Use Go stdlib net/http with Go 1.22+ pattern routing (mux.HandleFunc(\"GET /path\", handler), r.PathValue(\"id\")). Do NOT use external routers (chi, gorilla, gin).
- Use log/slog for logging. Do NOT use third-party loggers.
- Use database/sql directly. Do NOT use ORMs (gorm, ent, etc).
- Write idiomatic Go: PascalCase exports, camelCase unexported, error as last return value.
- Always handle errors. Wrap with context: fmt.Errorf(\"doing X: %%w\", err)
- Include all necessary imports in every file. Go files must compile independently.
- The design doc at docs/plans/2026-02-25-orchestrator-design.md has additional architecture context if needed.
- Phase 1 code is already in place. Read existing code to understand patterns before writing new code.
- The harness packages go under internal/harness/ (blueprint/, rules/, tools/, gates/)."

  log "  Running Claude for task ${task_id}..."

  claude -p "$prompt" \
    --model opus \
    --allowedTools "Bash,Read,Write,Edit,Glob,Grep,mcp__plugin_context7_context7__resolve-library-id,mcp__plugin_context7_context7__query-docs" \
    >> "$LOG_FILE" 2>&1 || true

  log_success "  Task ${task_id} completed"
}

# ══════════════════════════════════════════════════════════
#  Sanity checks: go build + go vet + go test
# ══════════════════════════════════════════════════════════
run_sanity_checks() {
  local phase="$1"
  log "  Running sanity checks for Phase ${phase}..."

  local check_output=""
  local exit_code=0

  log "    Running go build ./..."
  check_output=$(cd "$PROJECT_DIR" && go build ./... 2>&1) || exit_code=$?
  if [[ $exit_code -ne 0 ]]; then
    log_error "    go build failed"
    echo "$check_output" >> "$LOG_FILE"
    echo "$check_output"
    return 1
  fi
  log_success "    go build OK"

  exit_code=0
  log "    Running go vet ./..."
  check_output=$(cd "$PROJECT_DIR" && go vet ./... 2>&1) || exit_code=$?
  if [[ $exit_code -ne 0 ]]; then
    log_error "    go vet failed"
    echo "$check_output" >> "$LOG_FILE"
    echo "$check_output"
    return 1
  fi
  log_success "    go vet OK"

  exit_code=0
  log "    Running go test ./..."
  check_output=$(cd "$PROJECT_DIR" && go test ./... 2>&1) || exit_code=$?
  if [[ $exit_code -ne 0 ]]; then
    log_error "    go test failed"
    echo "$check_output" >> "$LOG_FILE"
    echo "$check_output"
    return 1
  fi
  log_success "    go test OK"

  log_success "  All sanity checks passed for Phase ${phase}"
  return 0
}

# ── Fix build errors via Claude ───────────────────────────
fix_build() {
  local phase="$1"
  local error_output="$2"
  local attempt="$3"

  log "  Fix attempt ${attempt}/${MAX_FIX_ATTEMPTS}..."

  local prompt="You are implementing a Go project called Deck — an agentic workflow orchestrator.

PROJECT DIRECTORY: $PROJECT_DIR

The build/validation failed after completing Phase ${phase}. Fix the errors below.

ERROR OUTPUT:
\`\`\`
${error_output}
\`\`\`

RULES:
- Read the relevant files to understand the context before fixing.
- Only fix what's broken. Do not refactor or change unrelated code.
- Read PRD.md if you need to understand the intended design.
- Read FINDINGS.md for context from previous tasks.
- After fixing, append a brief note to FINDINGS.md under '## Phase ${phase} — Build Fix (attempt ${attempt})' describing what went wrong and how you fixed it.
- Do NOT commit anything to git.
- Do NOT run the dev server.
- Use context7 MCP tools to look up Go library docs if you need to verify correct API usage.
- Use modernc.org/sqlite (pure Go, driver name \"sqlite\"), NOT mattn/go-sqlite3.
- Use Go stdlib net/http with Go 1.22+ routing. No external routers.
- Make sure all Go files compile with correct imports.
- IMPORTANT: Run go test ./... after fixing to verify tests pass too."

  claude -p "$prompt" \
    --model opus \
    --allowedTools "Bash,Read,Write,Edit,Glob,Grep,mcp__plugin_context7_context7__resolve-library-id,mcp__plugin_context7_context7__query-docs" \
    >> "$LOG_FILE" 2>&1 || true
}

# ── Commit a phase ────────────────────────────────────────
commit_phase() {
  local phase="$1"
  local phase_name="$2"

  log "  Committing Phase ${phase}..."
  cd "$PROJECT_DIR"
  git add -A
  if git diff --cached --quiet 2>/dev/null; then
    log "  No changes to commit for Phase ${phase} (already committed)"
  else
    git commit -m "$(cat <<EOF
phase 2.${phase}: ${phase_name}

Automated by ralph.sh (Phase 2: Harness Core)
EOF
)" 2>&1 | tee -a "$LOG_FILE"
    log_success "  Phase ${phase} committed"
  fi
}

# ── Main loop ─────────────────────────────────────────────
main() {
  echo "" > "$LOG_FILE"
  log "${BOLD}Ralph — Deck Phase 2 Harness Core Builder${NC}"
  log "Project: $PROJECT_DIR"
  log ""

  init_findings

  local current_phase=0

  for task_entry in "${TASKS[@]}"; do
    local task_id="${task_entry%%|*}"
    local remainder="${task_entry#*|}"
    local phase="${remainder%%|*}"
    local description="${remainder#*|}"

    # ── Phase boundary: sanity check + commit previous phase ──
    if [[ $phase -ne $current_phase ]]; then
      if [[ $current_phase -ne 0 ]]; then
        local error_output check_result
        error_output=$(run_sanity_checks "$current_phase" 2>&1) && check_result=0 || check_result=$?

        if [[ $check_result -ne 0 ]]; then
          local fixed=false
          for attempt in $(seq 1 $MAX_FIX_ATTEMPTS); do
            fix_build "$current_phase" "$error_output" "$attempt"
            error_output=$(run_sanity_checks "$current_phase" 2>&1) && check_result=0 || check_result=$?
            if [[ $check_result -eq 0 ]]; then
              fixed=true
              log_success "  Build fixed on attempt ${attempt}"
              break
            fi
          done

          if [[ "$fixed" != "true" ]]; then
            log_error "  Phase ${current_phase} could not be fixed after ${MAX_FIX_ATTEMPTS} attempts."
            log_error "  Halting. Check ralph.log for details."
            exit 1
          fi
        fi

        commit_phase "$current_phase" "$(get_phase_name $current_phase)"
      fi

      current_phase=$phase
      log_phase "$phase — $(get_phase_name $phase)"
    fi

    # ── Skip completed tasks ──
    if is_task_done "$task_id"; then
      log "  Skipping ${task_id} (already done)"
      continue
    fi

    # ── Execute task ──
    log "${YELLOW}► Task ${task_id}: ${description}${NC}"
    run_task "$task_id" "$description"
    mark_task_done "$task_id"
  done

  # ── Final phase: sanity check + commit ──
  if [[ $current_phase -ne 0 ]]; then
    local error_output check_result
    error_output=$(run_sanity_checks "$current_phase" 2>&1) && check_result=0 || check_result=$?

    if [[ $check_result -ne 0 ]]; then
      local fixed=false
      for attempt in $(seq 1 $MAX_FIX_ATTEMPTS); do
        fix_build "$current_phase" "$error_output" "$attempt"
        error_output=$(run_sanity_checks "$current_phase" 2>&1) && check_result=0 || check_result=$?
        if [[ $check_result -eq 0 ]]; then
          fixed=true
          log_success "  Build fixed on attempt ${attempt}"
          break
        fi
      done

      if [[ "$fixed" != "true" ]]; then
        log_error "  Final phase could not be fixed after ${MAX_FIX_ATTEMPTS} attempts."
        log_error "  Halting. Check ralph.log for details."
        exit 1
      fi
    fi

    commit_phase "$current_phase" "$(get_phase_name $current_phase)"
  fi

  echo ""
  log_success "${BOLD}Ralph complete! All 6 phases built and committed.${NC}"
  log "Check FINDINGS.md for decisions log."
  log "Check ralph.log for full output."
}

main "$@"
