#!/usr/bin/env zsh
# ralph.sh — Deck Phase 4 Execution Builder
# Executes tasks from PRD.md in headless mode with parallel task support.
# Runs sanity checks between phases. Self-heals on build failures (max 3 attempts).
# Commits once per phase. Tracks findings in FINDINGS.md.

set -euo pipefail

# ── Trap Ctrl+C to exit cleanly ──────────────────────────
cleanup() {
  echo ""
  echo -e "\033[0;31m[$(date '+%Y-%m-%d %H:%M:%S')] Ralph interrupted. Exiting.\033[0m"
  kill 0 2>/dev/null
  exit 130
}
trap cleanup SIGINT SIGTERM

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
PRD_FILE="$PROJECT_DIR/PRD.md"
FINDINGS_FILE="$PROJECT_DIR/FINDINGS.md"
LOG_FILE="$PROJECT_DIR/ralph.log"
MAX_FIX_ATTEMPTS=3

# ── Colors ────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
BOLD='\033[1m'
NC='\033[0m'

# ══════════════════════════════════════════════════════════
#  Task list — format: "task_id|phase|description"
#  Must match PRD.md checkboxes exactly.
# ══════════════════════════════════════════════════════════
TASKS=(
  "1.1|1|Create mail broker service"
  "1.2|1|Add mail HTTP routes"
  "2.1|2|Implement local sandbox provider"
  "2.2|2|Implement Claude Code agent runtime"
  "3.1|3|Create agent spawner service"
  "4.1|4|Create stream scheduler"
  "5.1|5|Implement deterministic and human step handlers"
  "6.1|6|Create execution coordinator"
  "7.1|7|Add execution management HTTP routes"
  "7.2|7|Add execution and mail client methods"
  "7.3|7|Create deck exec command"
  "7.4|7|Create deck agents command"
  "7.5|7|Create deck mail command"
  "8.1|8|Wire execution layer into daemon"
  "8.2|8|Add event-driven execution trigger"
  "8.3|8|Add unit tests"
)

# ══════════════════════════════════════════════════════════
#  Parallel groups — tasks that can run concurrently.
#  Format: space-separated task IDs per group.
#  Tasks not listed here run sequentially.
#  Within a phase, groups are processed in order:
#    first group runs in parallel, waits, then next group.
# ══════════════════════════════════════════════════════════
typeset -A PARALLEL_GROUPS
PARALLEL_GROUPS=(
  # Phase 2: sandbox provider + runtime are completely independent
  [2]="2.1 2.2"
  # Phase 7: routes + client methods are independent
  [7]="7.1 7.2"
  # Phase 7: CLI commands are independent (after 7.1 + 7.2)
  [7.batch]="7.3 7.4 7.5"
)

# ══════════════════════════════════════════════════════════
#  Phase names (for commit messages and logging)
# ══════════════════════════════════════════════════════════
get_phase_name() {
  case "$1" in
    1) echo "Mail Broker Service" ;;
    2) echo "Provider Implementations" ;;
    3) echo "Agent Spawner" ;;
    4) echo "Stream Scheduler" ;;
    5) echo "Blueprint Step Handlers" ;;
    6) echo "Execution Coordinator" ;;
    7) echo "API & CLI" ;;
    8) echo "Integration & Wiring" ;;
  esac
}

# ── Helpers ───────────────────────────────────────────────
timestamp() { date "+%Y-%m-%d %H:%M:%S" }

log() {
  echo -e "${CYAN}[$(timestamp)]${NC} $1" | tee -a "$LOG_FILE"
}

log_success() {
  echo -e "${GREEN}[$(timestamp)] ✓${NC} $1" | tee -a "$LOG_FILE"
}

log_error() {
  echo -e "${RED}[$(timestamp)] ✗${NC} $1" | tee -a "$LOG_FILE"
}

log_phase() {
  echo "" | tee -a "$LOG_FILE"
  echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a "$LOG_FILE"
  echo -e "${BOLD}${BLUE}  Phase $1${NC}" | tee -a "$LOG_FILE"
  echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a "$LOG_FILE"
}

# Check if a task is already marked done in PRD.md
is_task_done() {
  local task_id="$1"
  grep -q "\[x\] \*\*${task_id}\*\*" "$PRD_FILE" 2>/dev/null
}

# Mark a task as done in PRD.md ([ ] → [x])
# NOTE: macOS sed syntax. On Linux, change `sed -i ''` to `sed -i`
mark_task_done() {
  local task_id="$1"
  sed -i '' "s/- \[ \] \*\*${task_id}\*\*/- [x] **${task_id}**/" "$PRD_FILE"
}

# Check if a task ID is in a parallel group
is_in_parallel_group() {
  local task_id="$1"
  for key in ${(k)PARALLEL_GROUPS}; do
    local group="${PARALLEL_GROUPS[$key]}"
    for id in ${(s: :)group}; do
      [[ "$id" == "$task_id" ]] && return 0
    done
  done
  return 1
}

# Get the parallel group key for a task
get_parallel_group() {
  local task_id="$1"
  for key in ${(k)PARALLEL_GROUPS}; do
    local group="${PARALLEL_GROUPS[$key]}"
    for id in ${(s: :)group}; do
      [[ "$id" == "$task_id" ]] && echo "$key" && return 0
    done
  done
  echo ""
}

# ── Init findings file ────────────────────────────────────
init_findings() {
  if [[ ! -f "$FINDINGS_FILE" ]]; then
    cat > "$FINDINGS_FILE" << 'EOF'
# Phase 4: Execution — Findings & Decisions Log

Auto-generated by ralph. Each task logs its decisions and findings here.
Phase 1 findings: `docs/phase1/FINDINGS.md`
Phase 2 findings: `docs/phase2/FINDINGS.md`
Phase 3 findings: `docs/phase3/FINDINGS.md`

---

EOF
    log "Created FINDINGS.md"
  fi
}

# ══════════════════════════════════════════════════════════
#  Task execution prompt
# ══════════════════════════════════════════════════════════
run_task() {
  local task_id="$1"
  local description="$2"
  local log_suffix="${3:-}"  # optional suffix for parallel log files

  local task_log="$LOG_FILE"
  if [[ -n "$log_suffix" ]]; then
    task_log="${LOG_FILE%.log}.${task_id}.log"
  fi

  local prompt="You are implementing a Go project called Deck — an agentic workflow orchestrator.

PROJECT DIRECTORY: $PROJECT_DIR

YOUR TASK: Execute task **${task_id}** — \"${description}\"

Read the full task specification from PRD.md (task ${task_id}) and implement it exactly.
Read FINDINGS.md to understand any decisions or context from previous tasks.
Read docs/phase1/FINDINGS.md, docs/phase2/FINDINGS.md, and docs/phase3/FINDINGS.md for context from earlier phases.

RULES:
- Only do what this specific task requires. Do not touch other tasks.
- After completing the task, append your findings/decisions to FINDINGS.md under a heading '## Task ${task_id}: ${description}'.
  Include: what you did, any decisions you made, any issues encountered, and any notes for future tasks. Keep it concise (3-8 bullet points).
- If you encounter something that should be deferred to a later phase, append it to docs/DEFERRED.md under the '## From Phase 4 (Execution)' section. Follow the existing format.
- Do NOT commit anything to git.
- Do NOT run the dev server or any long-running processes.
- If a task says to create a file, create the file with the full implementation — not stubs or TODOs.
- Make sure all types and imports are correct. Every Go file must compile.
- IMPORTANT: Before using any Go library you're unfamiliar with, use the context7 MCP tools to look up documentation:
  1. First call mcp__plugin_context7_context7__resolve-library-id to find the library ID
  2. Then call mcp__plugin_context7_context7__query-docs with that ID and a specific query
  This applies to ALL external libraries and any Go stdlib packages you're not certain about.
- Use modernc.org/sqlite (pure Go driver, no CGo). The driver name is \"sqlite\". Do NOT use mattn/go-sqlite3.
- Use Go stdlib net/http with Go 1.22+ pattern routing (mux.HandleFunc(\"GET /path\", handler), r.PathValue(\"id\")). Do NOT use external routers.
- Use log/slog for logging. Do NOT use third-party loggers.
- Use database/sql directly. Do NOT use ORMs (gorm, ent, etc).
- Write idiomatic Go: PascalCase exports, camelCase unexported, error as last return value.
- Always handle errors. Wrap with context: fmt.Errorf(\"doing X: %%w\", err)
- Include all necessary imports in every file. Go files must compile independently.
- The design doc at docs/plans/2026-02-25-orchestrator-design.md has additional architecture context if needed.
- Phase 1, 2, and 3 code is already in place. Read existing code to understand patterns before writing new code.
- Follow the same store patterns as internal/db/objectives.go and internal/db/agents.go (UUID generation, Unix timestamps, JSON blob columns).
- Follow the same route patterns as internal/daemon/routes.go (writeJSON, writeError helpers, Go 1.22 path routing).
- Follow the same service patterns as internal/services/events/ for new service packages.
- The blueprint engine is in internal/harness/blueprint/ — read engine.go and types.go to understand StepHandler, StepResult, Execution, Step types.
- The sandbox interfaces are in internal/sandbox/ — read types.go and provider.go for the SandboxProvider and Sandbox interfaces.
- The agent runtime interfaces are in internal/runtime/runtime.go — read it for AgentRuntime, AgentProcess, AgentOpts, AgentMessage, AgentEvent, AgentResult types.
- The existing MailStore is in internal/db/mail.go — read it for the Send, GetUnread, MarkRead methods.
- The quality gate runner is in internal/harness/gates/ — read runner.go for the Runner interface.
- The agent overlay builder is in internal/services/agents/overlay.go — read it for BuildOverlay and BuildPlannerOverlay."

  log "  Running Claude for task ${task_id}..."

  claude -p "$prompt" \
    --model sonnet \
    --allowedTools "Bash,Read,Write,Edit,Glob,Grep,mcp__plugin_context7_context7__resolve-library-id,mcp__plugin_context7_context7__query-docs" \
    >> "$task_log" 2>&1 || true

  # Merge parallel task log into main log
  if [[ -n "$log_suffix" && -f "$task_log" ]]; then
    echo "── Task ${task_id} output ──" >> "$LOG_FILE"
    cat "$task_log" >> "$LOG_FILE"
    rm -f "$task_log"
  fi

  log_success "  Task ${task_id} completed"
}

# ══════════════════════════════════════════════════════════
#  Parallel task execution
#  Runs multiple tasks concurrently, waits for all to finish.
# ══════════════════════════════════════════════════════════
run_parallel_tasks() {
  local -a task_ids=("${@}")
  local pids=()
  local failed=false

  log "${MAGENTA}  Running ${#task_ids[@]} tasks in parallel: ${task_ids[*]}${NC}"

  for task_id in "${task_ids[@]}"; do
    if is_task_done "$task_id"; then
      log "  Skipping ${task_id} (already done)"
      continue
    fi

    # Look up description from TASKS array
    local description=""
    for task_entry in "${TASKS[@]}"; do
      local tid="${task_entry%%|*}"
      if [[ "$tid" == "$task_id" ]]; then
        local remainder="${task_entry#*|}"
        description="${remainder#*|}"
        break
      fi
    done

    log "${YELLOW}► Task ${task_id}: ${description} (parallel)${NC}"

    # Run in background subshell
    (
      run_task "$task_id" "$description" "parallel"
      mark_task_done "$task_id"
    ) &
    pids+=($!)
  done

  # Wait for all background tasks
  for pid in "${pids[@]}"; do
    if ! wait "$pid"; then
      log_error "  A parallel task (pid $pid) failed"
      failed=true
    fi
  done

  if [[ "$failed" == "true" ]]; then
    log_error "  Some parallel tasks failed. Continuing (claude exits are non-fatal)."
  fi

  log_success "  All parallel tasks finished"
}

# ══════════════════════════════════════════════════════════
#  Sanity checks: go build + go vet + go test
# ══════════════════════════════════════════════════════════
run_sanity_checks() {
  local phase="$1"
  log "  Running sanity checks for Phase ${phase}..."

  local check_output=""
  local exit_code=0

  log "    Running go build ./..."
  check_output=$(cd "$PROJECT_DIR" && go build ./... 2>&1) || exit_code=$?
  if [[ $exit_code -ne 0 ]]; then
    log_error "    go build failed"
    echo "$check_output" >> "$LOG_FILE"
    echo "$check_output"
    return 1
  fi
  log_success "    go build OK"

  exit_code=0
  log "    Running go vet ./..."
  check_output=$(cd "$PROJECT_DIR" && go vet ./... 2>&1) || exit_code=$?
  if [[ $exit_code -ne 0 ]]; then
    log_error "    go vet failed"
    echo "$check_output" >> "$LOG_FILE"
    echo "$check_output"
    return 1
  fi
  log_success "    go vet OK"

  # Run tests from Phase 8 onward (when test files exist)
  if [[ $phase -ge 8 ]]; then
    exit_code=0
    log "    Running go test ./..."
    check_output=$(cd "$PROJECT_DIR" && go test ./... 2>&1) || exit_code=$?
    if [[ $exit_code -ne 0 ]]; then
      log_error "    go test failed"
      echo "$check_output" >> "$LOG_FILE"
      echo "$check_output"
      return 1
    fi
    log_success "    go test OK"
  fi

  log_success "  All sanity checks passed for Phase ${phase}"
  return 0
}

# ── Fix build errors via Claude ───────────────────────────
fix_build() {
  local phase="$1"
  local error_output="$2"
  local attempt="$3"

  log "  Fix attempt ${attempt}/${MAX_FIX_ATTEMPTS}..."

  local prompt="You are implementing a Go project called Deck — an agentic workflow orchestrator.

PROJECT DIRECTORY: $PROJECT_DIR

The build/validation failed after completing Phase ${phase}. Fix the errors below.

ERROR OUTPUT:
\`\`\`
${error_output}
\`\`\`

RULES:
- Read the relevant files to understand the context before fixing.
- Only fix what's broken. Do not refactor or change unrelated code.
- Read PRD.md if you need to understand the intended design.
- Read FINDINGS.md for context from previous tasks.
- After fixing, append a brief note to FINDINGS.md under '## Phase ${phase} — Build Fix (attempt ${attempt})' describing what went wrong and how you fixed it.
- Do NOT commit anything to git.
- Do NOT run the dev server.
- Use context7 MCP tools to look up Go library docs if you need to verify correct API usage.
- Use modernc.org/sqlite (pure Go, driver name \"sqlite\"), NOT mattn/go-sqlite3.
- Use Go stdlib net/http with Go 1.22+ routing. No external routers.
- Make sure all Go files compile with correct imports.
- The blueprint engine types are in internal/harness/blueprint/types.go — check StepHandler, StepResult, Execution, Step signatures.
- The sandbox interfaces are in internal/sandbox/types.go — check Sandbox, SandboxProvider, CreateOpts, ExecResult.
- The runtime interfaces are in internal/runtime/runtime.go — check AgentRuntime, AgentProcess, AgentOpts.
- IMPORTANT: Run go build ./... and go vet ./... after fixing to verify the build passes."

  claude -p "$prompt" \
    --model sonnet \
    --allowedTools "Bash,Read,Write,Edit,Glob,Grep,mcp__plugin_context7_context7__resolve-library-id,mcp__plugin_context7_context7__query-docs" \
    >> "$LOG_FILE" 2>&1 || true
}

# ── Commit a phase ────────────────────────────────────────
commit_phase() {
  local phase="$1"
  local phase_name="$2"

  log "  Committing Phase ${phase}..."
  cd "$PROJECT_DIR"
  git add -A
  if git diff --cached --quiet 2>/dev/null; then
    log "  No changes to commit for Phase ${phase} (already committed)"
  else
    git commit -m "$(cat <<EOF
phase 4.${phase}: ${phase_name}

Automated by ralph.sh (Phase 4: Execution)
EOF
)" 2>&1 | tee -a "$LOG_FILE"
    log_success "  Phase ${phase} committed"
  fi
}

# ── Main loop ─────────────────────────────────────────────
main() {
  echo "" > "$LOG_FILE"
  log "${BOLD}Ralph — Deck Phase 4 Execution Builder${NC}"
  log "Project: $PROJECT_DIR"
  log ""

  init_findings

  local current_phase=0
  local -a processed_parallel_groups=()

  for task_entry in "${TASKS[@]}"; do
    local task_id="${task_entry%%|*}"
    local remainder="${task_entry#*|}"
    local phase="${remainder%%|*}"
    local description="${remainder#*|}"

    # ── Phase boundary: sanity check + commit previous phase ──
    if [[ $phase -ne $current_phase ]]; then
      if [[ $current_phase -ne 0 ]]; then
        local error_output check_result
        error_output=$(run_sanity_checks "$current_phase" 2>&1) && check_result=0 || check_result=$?

        if [[ $check_result -ne 0 ]]; then
          local fixed=false
          for attempt in $(seq 1 $MAX_FIX_ATTEMPTS); do
            fix_build "$current_phase" "$error_output" "$attempt"
            error_output=$(run_sanity_checks "$current_phase" 2>&1) && check_result=0 || check_result=$?
            if [[ $check_result -eq 0 ]]; then
              fixed=true
              log_success "  Build fixed on attempt ${attempt}"
              break
            fi
          done

          if [[ "$fixed" != "true" ]]; then
            log_error "  Phase ${current_phase} could not be fixed after ${MAX_FIX_ATTEMPTS} attempts."
            log_error "  Halting. Check ralph.log for details."
            exit 1
          fi
        fi

        commit_phase "$current_phase" "$(get_phase_name $current_phase)"
      fi

      current_phase=$phase
      processed_parallel_groups=()
      log_phase "$phase — $(get_phase_name $phase)"
    fi

    # ── Check if this task is part of a parallel group ──
    local group_key=$(get_parallel_group "$task_id")
    if [[ -n "$group_key" ]]; then
      # Skip if we already processed this parallel group
      local already_done=false
      if (( ${#processed_parallel_groups[@]} > 0 )); then
        for processed in "${processed_parallel_groups[@]}"; do
          [[ "$processed" == "$group_key" ]] && already_done=true && break
        done
      fi

      if [[ "$already_done" == "true" ]]; then
        continue
      fi

      # Run the entire parallel group
      local group_tasks=(${(s: :)PARALLEL_GROUPS[$group_key]})
      run_parallel_tasks "${group_tasks[@]}"
      processed_parallel_groups+=("$group_key")
      continue
    fi

    # ── Skip completed tasks ──
    if is_task_done "$task_id"; then
      log "  Skipping ${task_id} (already done)"
      continue
    fi

    # ── Execute task sequentially ──
    log "${YELLOW}► Task ${task_id}: ${description}${NC}"
    run_task "$task_id" "$description"
    mark_task_done "$task_id"
  done

  # ── Final phase: sanity check + commit ──
  if [[ $current_phase -ne 0 ]]; then
    local error_output check_result
    error_output=$(run_sanity_checks "$current_phase" 2>&1) && check_result=0 || check_result=$?

    if [[ $check_result -ne 0 ]]; then
      local fixed=false
      for attempt in $(seq 1 $MAX_FIX_ATTEMPTS); do
        fix_build "$current_phase" "$error_output" "$attempt"
        error_output=$(run_sanity_checks "$current_phase" 2>&1) && check_result=0 || check_result=$?
        if [[ $check_result -eq 0 ]]; then
          fixed=true
          log_success "  Build fixed on attempt ${attempt}"
          break
        fi
      done

      if [[ "$fixed" != "true" ]]; then
        log_error "  Final phase could not be fixed after ${MAX_FIX_ATTEMPTS} attempts."
        log_error "  Halting. Check ralph.log for details."
        exit 1
      fi
    fi

    commit_phase "$current_phase" "$(get_phase_name $current_phase)"
  fi

  echo ""
  log_success "${BOLD}Ralph complete! All 8 phases built and committed.${NC}"
  log "Check FINDINGS.md for decisions log."
  log "Check ralph.log for full output."
}

main "$@"
